In [2]:
import numpy as np
import torch
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
from modules import Net
net = Net()
chkpnt = torch.load(r'outputs/label_smooth/chkpnt.pt', map_location=device)
net.load_state_dict(chkpnt['model_dict'], strict=True)
net.eval()
del chkpnt

In [ ]:
import weightwatcher as ww
watcher = ww.WeightWatcher(model=net)
details = watcher.analyze(plot=True)

# model = models.vgg19_bn(pretrained=True)
# watcher = ww.WeightWatcher(model=model)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(202103014)

N = 5 # dimension of our square matrix

D = np.diag([0, 3 + 1j, 4 + 1j, 1 + 5j, 9 + 2j])
M = np.random.rand(N, N) + D

R = np.zeros(N) # disk radii
for i in range(N):
    R[i] = sum(abs(M[i,:])) - abs(M[i,i])

eigenvalues = np.linalg.eigvals(M)

# Plotting code
fig, ax = plt.subplots()
for k in range(N):
    x, y = M[k,k].real, M[k,k].imag
    ax.add_artist( plt.Circle((x, y), R[k], alpha=0.5) )
    plt.plot(eigenvalues[k].real, eigenvalues[k].imag, 'k+')

ax.axis([-4, 12.5, -4, 9])
ax.set_aspect(1)
ax.grid(True)
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.title("Gershgorin disks and eigenvalues $x + iy$")

In [27]:
targets = torch.Tensor([2, 3, 4]).long()
print(targets)
n_classes = 10

t = torch.empty(size=(targets.size(0), n_classes)).fill_(0).scatter_(1, targets.data.unsqueeze(1), 1.)
w = torch.rand_like(t)
w = w / w.sum(-1).view(-1, 1)
t


tensor([2, 3, 4])


tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [29]:
print(t.shape, targets.shape)
t = (1-w)*(t==1) + w * (t!=1)
t.sum(-1)

torch.Size([3, 10]) torch.Size([3])


tensor([1.0000, 1.0000, 1.0000])